services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  admin:
    build:
      context: ../
      dockerfile: infra/../src/admin_app/Dockerfile
    environment:
      - FLASK_APP=admin.py
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_FLASK=${SECRET_FLASK}
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "5000:5000"

  telegram-bot:
    build:
      context: ../
      dockerfile: infra/Dockerfile-telegram
    environment:
      - DATABASE_ASYNC_URL=${DATABASE_ASYNC_URL}
      - PYTHONPATH=/app/src
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
      - admin
    networks:
      - mynetwork
    command: >
      bash -c "python main.py"

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: