services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask-admin:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    environment:
      - FLASK_APP=admin.py
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app/src
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: >
      bash -c "flask run --host=0.0.0.0"

volumes:
  postgres_data:
