version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - turutin-network

  admin:
    depends_on:
      - db
    image: ${докерхаб_логин}/admin
    environment:
      - FLASK_APP=${FLASK_APP}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_FLASK=${SECRET_FLASK}
    networks:
      - mynetwork
    expose:
      - "8000"

  bot:
    depends_on:
      - db
      - admin
    image: ${докерхаб_логин}/bot
    environment:
      - DATABASE_ASYNC_URL=${DATABASE_ASYNC_URL}
      - PYTHONPATH=/app/src
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - turutin-network

  nginx:
    depends_on:
      - admin
      - bot
    image: ${докерхаб_логин}/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - turutin-network

networks:
  turutin-network:
    driver: bridge

volumes:
  postgres_data:
