services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - turutin-network

  admin:
    image: hihix/admin:latest
    environment:
      - FLASK_APP=${FLASK_APP}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_FLASK=${SECRET_FLASK}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
    networks:
      - turutin-network
    restart: unless-stopped
    ports:
      - "8000:8000"

  telegram-bot:
    image: hihix/bot:latest
    environment:
      - DATABASE_ASYNC_URL=${DATABASE_ASYNC_URL}
      - PYTHONPATH=/app/src
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
      - admin
    networks:
      - turutin-network
    restart: unless-stopped

networks:
  turutin-network:
    driver: bridge

volumes:
  postgres_data:

