services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=admin.py
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env

  alembic:
    build: .
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
